pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - check-success=build
      - check-success=unit
      - check-success=it
      - check-success=build-docker
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
